### PR TITLE
Use standard plot naming convention (plot-k32-<ymdhm>-<plotid>.plot).

### PR DESCRIPTION
**Pull request by mocksoul**
Also add .tmp suffix until complete

### CODE REVIEW

**Comment by harold-b** [comment]
Thanks for this 👍  Will try to review on Thursday, might no be able to tomorrow.

**Comment by maxcom99** [comment]
I had to manually merge this but it works perfectly, thank you!! @harold-b - please merge, thank you

**Comment by maxcom99** [comment]
@harold-b -- hey bud, any chance you can merge this?

**Comment by harold-b** [comment]
>  hey bud, any chance you can merge this?

Trying to, but been extremely busy with my job lately. But I haven't forgotten. Sorry I missed the window to review @mocksoul , trying my best to make some time this week...

**Pull request merged**
